#include <iostream>
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even valued terms.
using namespace std;

int main() {

int a;
int b;
int c=1;

for(a=1;a<4000000;a = b + c) {
	b = a + c; 
	c = b + a;
	
	
	
	
	}
	cout << a +2<< endl;
return 0;
}
